import { RegisterPage } from '@/features';
import Head from 'next/head';
import React from 'react';

const Register = () => {
    return (
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
                    rel="stylesheet"
                />
            </Head>
            <RegisterPage />
        </div>
    )
}

export default Register