import React from 'react'
import Head from "next/head";
import { Reyting } from '@/features';

const reyting = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Reyting />
    </>
  )
}

export default reyting